---
- name: Remove attribute mapping folder
  become: true
  vars:
    keystone: "{{ keystone_services['keystone'] }}"
  file:
    state: absent
    path: "{{ keystone_host_federation_attribute_mappings_folder }}"
  when:
    - inventory_hostname in groups[keystone.group]

- name: Create attribute mapping folder
  vars:
    keystone: "{{ keystone_services['keystone'] }}"
  file:
    dest: "{{ keystone_host_federation_attribute_mappings_folder }}"
    state: "directory"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[keystone.group]

- name: Copying OpenStack Identity Providers attribute mappings
  vars:
    keystone: "{{ keystone_services['keystone'] }}"
  become: true
  copy:
    src: "{{ item.file }}"
    dest: "{{ keystone_host_federation_attribute_mappings_folder }}/{{ item.file | basename }}"
    mode: "0660"
  with_items: "{{ keystone_identity_mappings }}"
  when:
    - inventory_hostname in groups[keystone.group]